spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tijdrame/tecnoTabSPringCloudConfig.git
          default-label: main

server:
  port: 8888