spring:
  application:
    name: currency-exchange-service
  h2:
    console:
      enabled: true
  jpa:
    #generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create

server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka